### ISSUE TITLE
Support for batch operations

### ISSUE THREAD

**Issue by jainrish** [igapyon/oiyokan-demosite#15]
Hi, I wanted to contribute support for batch operations. Let me know if you accept contributions

**Comment by igapyon** [comment]
Hi @jainrish -san
Contributions are expected to be gladly accepted.

Please send a Merge Request to the following repository Please allow me to review the contents.
https://github.com/igapyon/oiyokan

**Comment by jainrish** [comment]
sounds good, thanks
